version: '3'
services:
  dbservice:
    image: postgres:11
    # postgres has an issue with mounting volumes
    # this works: http://www.lukaszewczak.com/2016/09/run-postgresql-using-docker-with.html
    # volumes:
    #   - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mfg_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
  laravel-env:
    build: ./dockerfiles
    depends_on:
      - dbservice
    volumes:
      - ".:/var/www/laravel"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      - "./dockerfiles/config/php/php.ini:/etc/php/php.ini"
  nginx:
    image: nginx:latest
    depends_on:
      - laravel-env
    volumes:
      - ".:/var/www/laravel"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
